---
# vim:ft=ansible:ts=2:et:
- name: "Create UNIX user {{ item.name }}"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups | join(',') }}"
    password: "{{ item.password | default('!') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"

- name: Create unix user public_key authentication
  when: item.ssh is defined and item.ssh.public_key is defined
  block:
    - name: Create UNIX user ssh dir
      file:
        dest: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: 0700

    - name: Set UNIX user public SSH key
      copy:
        content: "{{ item.ssh.public_key }}"
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: 0644
