---
# vim:ft=ansible:ts=2:et:

- name: Create extra groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    system: "{{ item.system | default(False) }}"
    gid: "{{ item.gid | d(omit) }}"
    state: present
  with_items: "{{ _unix_users.groups }}"

- name: Set /etc/sudoers to allow passwordless sudo for admin group members
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    line: '%admin ALL = NOPASSWD: ALL'
    insertafter: '^%sudo(\\s+)ALL'
    validate: 'visudo -cf %s'

- name: Include add tasks
  ansible.builtin.include_tasks: add.yml
  with_items: "{{ _unix_users.users }}"
  when: item.state is not defined or item.state == "present"

- name: Include remove tasks
  ansible.builtin.include_tasks: remove.yml
  with_items: "{{ _unix_users.users }}"
  when: item.state is defined and item.state == "absent"
