---
# vim:ft=ansible:ts=2:et:
- name: "Remove UNIX user {{ item.name }}"
  user:
    name: "{{ item.name }}"
    state: absent

- name: Delete UNIX user's ssh dir
  file:
    dest: "/home/{{ item.name }}"
    state: absent
