---
# vim:ft=ansible:ts=2:et:
- name: "Remove UNIX user {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: absent

- name: Delete UNIX user's ssh dir
  ansible.builtin.file:
    dest: "/home/{{ item.name }}"
    state: absent
